name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate output file
      run: |
        ./target/debug/uemura > nestest.log
    - name: Compare output
      run: |
        diff --brief nestest.log golden_standard_no_cycles.log || (echo "Files are different" && exit 1)
